const assert=require('node:assert/strict');
require('./cloud-core.js');
const {diff,reconcile,unpack,equal}=globalThis.OrdenProCloudCore;
const empty={orders:[],quotes:[],invoices:[]};
const base={ordenpro_orders:[{id:'1',version:3,data:{id:'1',name:'A'}}],ordenpro_quotes:[],ordenpro_invoices:[]};
assert(equal({a:1,b:2},{b:2,a:1}));
assert.deepEqual(diff(unpack(base),base),[]);
assert.equal(diff(empty,base)[0].deleted,true);
assert.equal(diff({ ...empty,orders:[{id:'1',name:'B'}]},base)[0].version,3);
const sent=unpack(base), current={...empty,orders:[{id:'1',name:'editado durante envío'}]};
const remote={...base,ordenpro_orders:[...base.ordenpro_orders,{id:'2',version:1,data:{id:'2',name:'otro dispositivo'}}]};
const merged=reconcile(sent,current,remote);
assert.equal(merged.orders[0].name,'editado durante envío');
assert.equal(merged.orders[1].id,'2');
assert.deepEqual(reconcile(sent,empty,remote).orders,[{id:'2',name:'otro dispositivo'}]);
assert.throws(()=>diff({...empty,orders:[{id:'1'},{id:'1'}]},base));
assert.throws(()=>diff({...empty,orders:[{name:'sin id'}]},base));
const deleted={...base,ordenpro_orders:[{...base.ordenpro_orders[0],deleted_at:'2026-10-07'}]};
assert.deepEqual(unpack(deleted),empty);
assert.equal(diff(sent,deleted)[0].version,3);
console.log('9 comprobaciones de comparación, borrado y cambios simultáneos correctas.');
