(function(){
'use strict';
const $=id=>document.getElementById(id),money=n=>n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
let saved=null;
const defaults={format:'A5',copies:100,colorPages:32,bwPages:0,coverMode:'color',innerW:45,innerH:64,innerPrice:26.7,coverW:45,coverH:64,coverPrice:81,innerMarkup:0,coverMarkup:0,covers:2,waste:0,binding:true,lamination:false,designEnabled:true,designPages:'',designPrice:5};
const fields=Object.keys(defaults);
function input(k,label,type='number',options){
 const cls='w-full bg-slate-900 border border-slate-700 rounded-lg p-2 text-slate-100';
 const control=options?`<select id="mag_${k}" class="${cls}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`:`<input id="mag_${k}" type="${type}" ${type==='number'?'min="0" step="any"':''} class="${cls}">`;
 return `<label class="block text-xs text-slate-300">${label}${control}</label>`;
}
const dialog=document.createElement('dialog');dialog.id='magazineDialog';dialog.className='bg-slate-800 text-slate-100 rounded-xl border border-slate-600 p-4 w-full max-w-2xl';
dialog.style.maxHeight='90vh';
dialog.innerHTML=`<div class="flex justify-between mb-3"><h2 class="text-lg font-semibold text-amber-400">Presupuesto de revistas</h2><button type="button" id="mag_close" aria-label="Cerrar">✕</button></div><form id="mag_form"><div class="grid grid-cols-2 sm:grid-cols-3 gap-3">${input('format','Formato','text',[['A5','A5 · 14,8 × 21 cm'],['16x22','16 × 22 cm'],['A4','A4 · 21 × 29,7 cm']])}${input('copies','Número de revistas')}${input('colorPages','Páginas interiores a color')}${input('bwPages','Páginas interiores en B/N')}${input('coverMode','Impresión portada · dos caras','text',[['color','Color'],['bw','Blanco y negro']])}${input('covers','Portadas por pliego 45 × 32','text',[[1,'Una'],[2,'Dos']])}</div><p class="text-xs text-slate-400 mt-3" id="mag_layout"></p><p class="text-xs text-slate-400 mt-2">Cada cara repite una misma página: se cobra entera a color o en blanco y negro.</p><h3 class="text-emerald-400 mt-4 mb-2">Interior · Estucado mate 130 g</h3><div class="grid grid-cols-2 gap-3">${input('innerW','Ancho de compra (cm)')}${input('innerH','Largo de compra (cm)')}${input('innerPrice','Coste resma · 500 pliegos (€)')}${input('innerMarkup','Recargo sobre el papel (%)')}</div><h3 class="text-emerald-400 mt-4 mb-2">Portada · Cartulina 350 g</h3><div class="grid grid-cols-2 gap-3">${input('coverW','Ancho de compra (cm)')}${input('coverH','Largo de compra (cm)')}${input('coverPrice','Coste resma · 500 pliegos (€)')}${input('coverMarkup','Recargo sobre el papel (%)')}${input('waste','Papel extra por merma (%)')}</div><h3 class="text-emerald-400 mt-4 mb-2">Diseño y maquetación</h3><label class="block text-sm mb-2"><input type="checkbox" id="mag_designEnabled"> Cobrar diseño (desmarca si viene ya diseñada)</label><div class="grid grid-cols-2 gap-3">${input('designPages','Páginas a diseñar (vacío = interiores)')}${input('designPrice','Precio de diseño por página (€)')}</div><p class="text-xs text-slate-400 mt-2">El diseño se cobra una sola vez, sin multiplicarlo por la tirada. Puedes cambiar las páginas para incluir la portada.</p><div class="flex flex-wrap gap-4 my-4"><label><input type="checkbox" id="mag_binding"> Fresado</label><label><input type="checkbox" id="mag_lamination"> Laminado · 45 € por tirada</label></div><div id="mag_result" class="bg-slate-900 rounded-lg p-3 text-sm space-y-1" aria-live="polite"></div><p class="text-xs text-slate-400 my-3">Precio antes de IVA. La merma añade papel, sin golpes adicionales. Al aplicar se sustituyen las impresiones y los conceptos de revistas anteriores. El recargo general del formulario se aplica después a todos los conceptos.</p><button type="submit" class="bg-amber-600 hover:bg-amber-500 rounded-lg px-4 py-2 font-semibold">Aplicar al presupuesto</button></form>`;
document.body.append(dialog);
function read(){return Object.fromEntries(fields.map(k=>[k,typeof defaults[k]==='boolean'?$('mag_'+k).checked:$('mag_'+k).value]));}
function fill(p){if(p.designEnabled===undefined)p={...p,designEnabled:false};if(p.colorPages===undefined)p={...p,colorPages:p.innerMode==='bw'?0:(p.pages||32),bwPages:p.innerMode==='bw'?(p.pages||32):0,colorFaces:''};for(const k of fields){const v=p[k]??defaults[k];if(typeof defaults[k]==='boolean')$('mag_'+k).checked=v;else $('mag_'+k).value=v;}preview();}
function preview(){const values=read();$('mag_designPages').disabled=!values.designEnabled;$('mag_designPrice').disabled=!values.designEnabled;try{const p=values,r=OrdenProMagazine.calculate(p),f=OrdenProMagazine.formats[p.format];$('mag_layout').textContent=`Interior: ${f.w} × ${f.h} cm · ${f.pages} repeticiones de la misma página por cara. Portada: 45 × 32 cm · dos caras.`;
 $('mag_result').innerHTML=`<p>Interior: ${r.innerSheets} pliegos de impresión · ${r.innerHits} golpes</p><p>Portada: ${r.coverSheets} pliegos de impresión · ${r.coverHits} golpes</p><p>Total: ${r.hits} golpes · color ${r.colorRate} €/golpe · B/N ${r.bwRate} €/golpe</p><p>Papel interior: ${r.innerParents} pliegos de compra · coste ${money(r.innerCost)} · venta ${money(r.innerSale)}</p><p>Papel portada: ${r.coverParents} pliegos de compra · coste ${money(r.coverCost)} · venta ${money(r.coverSale)}</p><p>Diseño: ${r.designPages} páginas × ${money(r.designPrice)} = ${money(r.design)}</p><p>Fresado: ${money(r.binding)} · Laminado: ${money(r.lamination)}</p>${r.spareCopies?`<p class="text-amber-300">Interior: se reservan ${r.spareCopies} juegos adicionales por el aprovechamiento del pliego.</p>`:''}<p class="text-lg text-emerald-400 font-bold">${money(r.total)} · ${money(r.unit)} por revista</p>`;return {p,r};
 }catch(e){$('mag_result').textContent=e.message;return null;}}
$('mag_form').addEventListener('input',preview);
$('mag_format').addEventListener('change',()=>{const f=OrdenProMagazine.formats[$('mag_format').value];for(const [k,v] of Object.entries({innerW:f.parentW,innerH:f.parentH,innerPrice:f.price,covers:f.covers}))$('mag_'+k).value=v;preview();});
for(const k of ['innerW','innerH'])$('mag_'+k).addEventListener('change',()=>{const p=read();if(+p.innerW===52&&+p.innerH===70)$('mag_innerPrice').value=33.7;else if(+p.innerW===45&&+p.innerH===64)$('mag_innerPrice').value=26.7;preview();});
$('mag_close').onclick=()=>dialog.close();
$('mag_form').onsubmit=e=>{e.preventDefault();const result=preview();if(!result)return;const {p,r}=result;
 if(!confirm('Aplicar el cálculo sustituirá las impresiones actuales y los conceptos de revistas anteriores. ¿Continuar?'))return;
 const keep=collectCustomCostRows().filter(row=>!row.name.startsWith('Revistas · '));resetCustomCostRows();keep.forEach(addCustomCostRow);
 [['Papel interior',r.innerSale],['Papel portada',r.coverSale],['Fresado',r.binding],['Laminado',r.lamination],['Diseño',r.design]].forEach(([name,amount])=>{if(amount)addCustomCostRow({name:'Revistas · '+name,amount:amount.toFixed(2)});});
 for(const [type,qty,price] of [['Color',r.colorHits,r.colorRate],['BW',r.bwHits,r.bwRate]]){$('print'+type+'Qty').value=qty;$('print'+type+'Price').value=price;updateImpresionesDisplay(type);}
 saved={...p,result:r};$('jobQuantity').value=p.copies;$('jobFormat').value=p.format==='16x22'?'16 × 22 cm':p.format;$('jobPaper').value='Interior estucado mate 130 g · Portada cartulina 350 g';$('jobFinishing').value=[p.binding?'Fresado':'',p.lamination?'Laminado':''].filter(Boolean).join(' · ');if(!$('jobTitle').value)$('jobTitle').value='Revistas '+$('jobFormat').value;
 updateCostTotals();dialog.close();};
window.ordenproMagazineUI={open(){fill(saved||{...defaults,copies:Number($('jobQuantity').value)||100});dialog.showModal();},load(p){saved=p?JSON.parse(JSON.stringify(p)):null;},readSaved(){return saved?JSON.parse(JSON.stringify(saved)):null;}};
})();
