const assert=require('node:assert/strict');const {calculate,yieldSheets}=require('./magazine-core.js');
const p={format:'A5',copies:100,colorPages:32,bwPages:0,coverMode:'color',innerW:45,innerH:64,coverW:45,coverH:64,innerPrice:26.7,coverPrice:81,innerMarkup:30,coverMarkup:20,covers:2,waste:0,binding:true,lamination:true};
let r=calculate(p);assert.equal(r.innerSheets,400);assert.equal(r.hits,900);assert.equal(r.innerParents,200);assert.equal(r.innerCost,10.68);
assert.equal(yieldSheets(52,70,46,33),2);
r=calculate({...p,colorPages:8,bwPages:24});assert.equal(r.colorHits,300);assert.equal(r.bwHits,600);
r=calculate({...p,copies:101,colorPages:8,bwPages:24});assert.equal(r.batches,26);assert.equal(r.innerHits,832);assert.equal(r.colorHits,310);assert.equal(r.bwHits,624);assert.equal(r.innerSheets,416);assert.equal(r.coverSheets,51);assert.equal(r.spareCopies,3);
r=calculate({...p,format:'A4',covers:1,copies:101,colorPages:8,bwPages:24});assert.equal(r.batches,51);assert.equal(r.innerHits,1632);assert.equal(r.colorHits,610);assert.equal(r.bwHits,1224);
r=calculate({...p,format:'16x22',innerW:52,innerH:70,covers:1});assert.equal(r.hits,1000);assert.equal(r.colorRate,.23);
r=calculate({...p,copies:10,colorPages:30});assert.equal(r.hits,100);assert.equal(r.colorRate,1);
r=calculate({...p,copies:10,colorPages:32});assert.equal(r.hits,106);assert.equal(r.colorRate,.825);
for(const [copies,expected] of [[1,20],[10,30],[50,90],[100,120],[200,180],[300,220],[500,270],[501,270],[540,270],[541,270.5],[600,300]])assert.equal(calculate({...p,copies}).binding,expected);
const base=calculate(p).total;r=calculate({...p,designEnabled:true,designPages:'',designPrice:5});assert.equal(r.design,160);assert.equal(r.total,base+160);
assert.equal(calculate({...p,copies:500,designEnabled:true,designPages:32,designPrice:5}).design,160);
assert.equal(calculate({...p,designEnabled:true,designPages:36,designPrice:7}).design,252);
assert.equal(calculate({...p,designEnabled:false,designPages:36,designPrice:7}).design,0);
assert.equal(calculate({...p,designEnabled:true,designPages:36,designPrice:0}).design,0);
assert.throws(()=>calculate({...p,colorPages:31}));assert.throws(()=>calculate({...p,colorPages:1.5}));assert.throws(()=>calculate({...p,innerW:20,innerH:20}));
// Legacy saved interior settings remain usable when explicitly recalculated.
r=calculate({...p,colorPages:undefined,bwPages:undefined,pages:32,innerMode:'bw'});assert.equal(r.colorHits,100);assert.equal(r.bwHits,800);
console.log('Repeated-page imposition, mixed modes, rounding, tiers, binding and design: passed');
