const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),core=require('./plotter-core');
const index=(name,size)=>core.products.findIndex(p=>p.name===name&&(!size||p.size===size));
const q={product:0,qty:1,width:100,height:100,price:21};
const canvas={...q,product:index('Lienzo sin bastidor','50×50 cm'),price:69,qty:2,frame:true};
assert.equal(core.calculate(canvas).frameMeters,4);assert.equal(core.calculate(canvas).total,178);
assert.equal(core.calculate({...canvas,frame:false}).total,138);
assert.equal(core.calculate({...q,product:index('Lona'),price:30,withEyelets:true,eyelets:8}).total,38);
assert.equal(core.calculate({...q,withEyelets:true,eyelets:8,withHanger:true,hangers:10}).total,21);
assert.equal(core.calculate({...q,product:index('PVC 5 mm · vinilo + laminado','A4'),price:25,qty:2,withHanger:true,hangers:2}).total,62);
assert.equal(core.calculate({...q,product:index('Vinilo tintado de cristales'),price:36}).total,36);
assert.equal(core.calculate({...q,product:index('Roll Up · 2,04 × 0,85 m'),price:90,qty:2,withHanger:true,withEyelets:true}).total,180);
assert.throws(()=>core.calculate({...q,product:index('Vinilo monomérico silueteado pequeño')}));
assert.throws(()=>core.calculate({...q,price:''}));
assert.equal(core.migrate({...q,result:{total:123.45}})[0].result.total,123.45);
const els=new Map();const get=id=>{if(!els.has(id))els.set(id,{value:'',checked:false,style:{},hidden:false,dataset:{},innerHTML:'',querySelectorAll:()=>[],addEventListener(t,f){const old=this[t];this[t]=old?(...a)=>{old(...a);f(...a)}:f;}});return els.get(id)};
let rows=[{name:'Montaje',amount:20}],c={OrdenProPlotter:core,document:{getElementById:get,createElement(){return {style:{},showModal(){},close(){}}},body:{append(){}}},confirm:()=>true,alert:()=>{},collectCustomCostRows:()=>rows,resetCustomCostRows:()=>rows=[],addCustomCostRow:r=>rows.push(r),updateCostTotals:()=>{}};
c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('plotter-ui.js','utf8'),c);
c.ordenproPlotterUI.open();assert.equal(get('plt_eyeletBlock').hidden,true);get('plt_notes').value='Foto familiar <Galo>\nLienzo del salón';get('plt_form').onsubmit({preventDefault(){}});
get('plt_tabs').click({target:{dataset:{category:'materials'}}});get('plt_product').value=index('Lona');get('plt_product').change();assert.equal(get('plt_eyeletBlock').hidden,false);get('plt_withEyelets').checked=true;get('plt_eyelets').value=8;get('plt_form').onsubmit({preventDefault(){}});
get('plt_apply').onclick();assert.equal(rows.length,3);assert.equal(rows[1].amount,'25.00');assert.equal(rows[2].amount,'38.00');
const saved=c.ordenproPlotterUI.readSaved();assert.equal(saved.version,2);assert.equal(saved.items.length,2);assert.equal(saved.items[0].notes,'Foto familiar <Galo>\nLienzo del salón');assert.equal(rows[1].notes,saved.items[0].notes);assert.ok(get('plt_items').innerHTML.includes('&lt;Galo&gt;'));
c.ordenproPlotterUI.open();get('plt_apply').onclick();assert.equal(rows.length,3);
get('plt_items').click({target:{dataset:{action:'duplicate',index:'0'}}});get('plt_apply').onclick();assert.equal(rows.length,4);assert.equal(rows[3].notes,rows[1].notes);
get('plt_items').click({target:{dataset:{action:'delete',index:'2'}}});get('plt_apply').onclick();assert.equal(rows.length,3);
c.ordenproPlotterUI.load({...q,result:{total:123.45}});c.ordenproPlotterUI.open();get('plt_apply').onclick();assert.equal(rows[1].amount,'123.45');
// Test final discount shared by forms, saved orders, summary and printable invoice.
const html=fs.readFileSync('index.html','utf8'),body=html.match(/function calculateCosts\(c\) \{([\s\S]*?)\n        \}/)[1],cost=Function('c',body);
const values={costPhotocomposition:100,costManipulado:20,laborHours:2,laborPricePerHour:30,travelKm:0,travelPricePerKm:0,printColorQty:0,printColorPrice:0,printBWQty:0,printBWPrice:0,vinylPolyAmount:0,vinylMonoAmount:0,vinylCutAmount:0,laminadoAmount:0,customCostAmount:50,otherCostAmount:0,marginPercent:20,discountPercent:10};
assert.equal(cost(values).total,248.4);assert.equal(cost({...values,discountPercent:100}).total,0);assert.equal(cost({...values,discountPercent:undefined}).total,276);
for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
console.log('Product extras, multiline persistence, legacy preservation and final discount passed');
