(function(){
'use strict';
const $=id=>document.getElementById(id),money=n=>n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
let saved=null;
const defaults={product:0,qty:1,width:100,height:100,price:21,laminate:false,lamPrice:18,eyelets:0,eyeletPrice:1,hangers:0,hangerPrice:6,minimum:0,discount:0};
function field(k,label){return '<label class="block text-xs text-slate-300">'+label+'<input id="plt_'+k+'" type="number" min="0" step="any" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-2 text-slate-100"></label>';}
const dialog=document.createElement('dialog');dialog.className='bg-slate-800 text-slate-100 rounded-xl border border-slate-600 p-4 w-full max-w-2xl';dialog.style.maxHeight='90vh';
dialog.innerHTML='<div class="flex justify-between mb-3"><h2 class="text-lg font-semibold text-emerald-400">Presupuesto de plotter</h2><button type="button" id="plt_close" aria-label="Cerrar">✕</button></div><form id="plt_form"><label class="block text-sm mb-3">Producto y formato<select id="plt_product" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-2">'+OrdenProPlotter.products.map((p,i)=>'<option value="'+i+'">'+p.name+(p.size?' · '+p.size:'')+' · '+(p.price==null?'precio pendiente':p.price+' €/'+p.unit)+'</option>').join('')+'</select></label><div class="grid grid-cols-2 gap-3">'+field('qty','Cantidad de piezas')+field('price','Precio tarifa editable')+field('width','Ancho de cada pieza (cm)')+field('height','Alto de cada pieza (cm)')+'</div><p id="plt_hint" class="text-xs text-amber-300 mt-2"></p><h3 class="mt-4 mb-2 text-emerald-400">Extras y descuento</h3><label><input type="checkbox" id="plt_laminate"> Añadir laminado (solo si no viene incluido)</label><div class="grid grid-cols-2 gap-3 mt-2">'+field('lamPrice','Laminado adicional (€/m²)')+field('eyelets','Ojales totales del trabajo')+field('eyeletPrice','Precio por ojal (€)')+field('hangers','Colgadores totales del trabajo')+field('hangerPrice','Precio por colgador (€)')+field('minimum','Importe mínimo del trabajo (€)')+field('discount','Descuento final (%)')+'</div><p class="text-xs text-slate-400 my-3">Tarifas de venta de referencia, antes de IVA. Los extras son totales, sin multiplicarlos otra vez por las piezas. Añade diseño, montaje o desplazamiento en los apartados del presupuesto.</p><div id="plt_result" aria-live="polite" class="bg-slate-900 rounded-lg p-3 my-3"></div><button type="submit" class="bg-emerald-600 rounded-lg px-4 py-2 font-semibold">Aplicar al presupuesto</button></form>';document.body.append(dialog);
function read(){return Object.fromEntries(Object.keys(defaults).map(k=>[k,typeof defaults[k]==='boolean'?$('plt_'+k).checked:$('plt_'+k).value]));}
function preview(){try{const p=read(),r=OrdenProPlotter.calculate(p),product=OrdenProPlotter.products[+p.product];$('plt_hint').textContent=product.unit==='m²'?'Precio por m² · superficie total: '+r.area.toFixed(3)+' m²':'Precio por unidad del formato seleccionado. Las medidas solo se usan para el laminado adicional.';$('plt_result').textContent='Producto: '+money(r.base)+' · Laminado extra: '+money(r.lamination)+' · Extras: '+money(r.extras)+' · Antes de descuento: '+money(r.subtotal)+' · Descuento: '+money(r.discountAmount)+' · Total: '+money(r.total)+' · '+money(r.unit)+' por pieza';return {p,r};}catch(e){$('plt_result').textContent=e.message;return null;}}
$('plt_product').addEventListener('change',()=>{const p=OrdenProPlotter.products[+$('plt_product').value];$('plt_price').value=p.price??'';$('plt_laminate').checked=false;preview();});
$('plt_form').addEventListener('input',preview);$('plt_close').onclick=()=>dialog.close();
$('plt_form').onsubmit=e=>{e.preventDefault();const result=preview();if(!result)return;if(!confirm('Sustituir los conceptos de plotter anteriores por este cálculo?'))return;const {p,r}=result,product=OrdenProPlotter.products[+p.product];const keep=collectCustomCostRows().filter(row=>!row.name.startsWith('Plotter · '));resetCustomCostRows();keep.forEach(addCustomCostRow);addCustomCostRow({name:'Plotter · '+product.name+(product.size?' · '+product.size:'')+' · '+p.qty+' piezas'+(+p.discount?' · descuento '+p.discount+'%':''),amount:r.total.toFixed(2)});saved={...p,result:r};$('jobQuantity').value=p.qty;if(!$('jobTitle').value)$('jobTitle').value=product.name;updateCostTotals();dialog.close();};
window.ordenproPlotterUI={open(){const p=saved||defaults;for(const k of Object.keys(defaults)){if(typeof defaults[k]==='boolean')$('plt_'+k).checked=p[k]??defaults[k];else $('plt_'+k).value=p[k]??defaults[k];}preview();dialog.showModal();},load(p){saved=p?JSON.parse(JSON.stringify(p)):null;},readSaved(){return saved?JSON.parse(JSON.stringify(saved)):null;}};
})();
